name: Report to Moodle Workflow incl Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    uses: BZZ-Commons/workflows/.github/workflows/linter.yml@main
    with:
      MOODLE: true  # CHANGE true=export grade to moodle
    secrets: inherit